#! /bin/bash

echo "purpose: decode svn repo to /mnt/clnx_shared/svn_syncdec"
echo -n "insert passwd:"
read passwd
# creating dirs
find /mnt/clnx_shared/My\ Dropbox/svn_syncenc/ -type d | sed -e 's#/mnt/clnx_shared/My\\ Dropbox/svn_syncenc#/mnt/clnx_shared/svn_syncdec#' | xargs -i{} mkdir -p "{}"
# decode all
rsync -avz --recursive /mnt/clnx_shared/My\ Dropbox/svn_syncenc/ /mnt/clnx_shared/svn_syncdec/ | \
    xargs -i{} sh -c "if [ -f "/mnt/clnx_shared/My\ Dropbox/svn_syncenc/{}\"" ]; then \
openssl aes-256-cbc -d -a -in /mnt/clnx_shared/My\ Dropbox/svn_syncenc/{} -out /mnt/clnx_shared/svn_syncdec/{} -pass pass:$passwd; fi"
